version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork
  flaskapp:
    image: flask-app-4
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork: